### ISSUE TITLE
CSP add report-uri

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/w3link#33]
We should have an API where we can receive reports from URIs being blocked by CSP, so that we can have a picture of how this affects users, as well as how we can make it better.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#reporting_directives

report-uri Instructs the user agent to report attempts to violate the Content Security Policy. These violation reports consist of [JSON](https://developer.mozilla.org/en-US/docs/Glossary/JSON) documents sent via an HTTP POST request to the specified URI

cc @jchris

**Comment by jchris** [comment]
@heyjay44 this is related to a bug report / fix for hosting HTML apps on or gateway.

* timely (capturing a snapshot of our usage as people were doing before a recent policy change, so if we wait too long those errors will taper off) 
* lightweight (I think only a few lines of code plus test and release cycle) 
* independent (could be shipped with or without other changes going on)

I'm not saying we should change the schedule for it but if it sneaks in, that's why :) 

PS here is a screenshot of how our policy change can impact apps that were running previously:

![image](https://user-images.githubusercontent.com/253/207889020-af6103fb-7f18-4ffb-ae7c-9a7eea34e44a.png)
